cluster.name: "docker-cluster"
network.host: 0.0.0.0

# Use single node discovery in order to disable production mode and # avoid bootstrap checks
discovery.type: single-node

# fix config mount
xpack.security.enabled: false

# fix logstash internal comms
xpack.security.http.ssl.enabled: false
